<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Description>Microsoft Dependency Injection extensions for CommandLineParser (https://github.com/commandlineparser/commandline)</Description>
    <PackageReleaseNotes>Added support for Async parsing/execution.</PackageReleaseNotes>
    <Product>CommandLineParser.DependencyInjection</Product>
    <PackageId>CommandLineParser.DependencyInjection</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>1.5</Version>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <Company>CommandLineParser.DependencyInjection</Company>
    <Authors>CommandLineParser.DependencyInjection</Authors>
      <PackageReadmeFile>readme.md</PackageReadmeFile>
      <PackageLicenseFile>license.txt</PackageLicenseFile>
      <Copyright>Jaron Horst</Copyright>
      <PackageProjectUrl>https://github.com/JaronrH/CommandLineParser.DependencyInjection</PackageProjectUrl>
      <RepositoryUrl>https://github.com/JaronrH/CommandLineParser.DependencyInjection</RepositoryUrl>
      <LangVersion>latest</LangVersion>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

	<ItemGroup>
		<None Include="..\readme.md" Pack="true" PackagePath="\" />
		<None Include="..\license.txt" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
